# Generated by Django 3.0.2 on 2021-03-07 03:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appSocial', '0004_auto_20210306_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasveer',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
