# Generated by Django 3.0.2 on 2021-03-07 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appSocial', '0005_tasveer_upload_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasveer',
            options={'ordering': ['-upload_date']},
        ),
    ]
