# Generated by Django 3.0.2 on 2021-03-08 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appSocial', '0008_like_likes_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='likes_count',
        ),
    ]
