# Generated by Django 3.0.2 on 2021-03-10 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSocial', '0011_auto_20210309_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasveer',
            name='your_say',
            field=models.TextField(blank=True),
        ),
    ]
