# Generated by Django 3.0.2 on 2021-03-13 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSocial', '0012_auto_20210309_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasveer',
            name='isVideo',
            field=models.BooleanField(default=False),
        ),
    ]
