# Generated by Django 3.0.2 on 2021-03-13 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSocial', '0013_tasveer_isvideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasveer',
            name='your_image',
            field=models.FileField(upload_to=''),
        ),
    ]
