# Generated by Django 3.0.2 on 2021-03-14 04:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appSocial', '0015_likecomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='likecomment',
            name='comment_liked',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
